version: "3.7"

# NOTE: If you're selfhosting, you'll find it much easier (and more performant) to use the proper selfhosted
# dockerfile that exists here: https://github.com/julianpoy/recipesage-selfhost

services:
  recipesage-monorepo: &recipesage-monorepo
    depends_on:
      - postgres
      - elasticsearch
      - pushpin
      - browserless
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./packages:/app/packages
  proxy:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    command: nginx -g 'daemon off;'
    depends_on:
      - frontend
      - backend
      - pushpin
  frontend:
    <<: *recipesage-monorepo
    ports:
      - "8100:8100"
    command: npx nx start frontend
  backend:
    <<: *recipesage-monorepo
    ports:
      - "3000:3000"
    command: ./scripts/watchandrun.sh 'npx ts-node --swc --project packages/backend/tsconfig.json packages/backend/src/bin/www' ./packages/backend ./packages/trpc ./packages/util ./packages/prisma
    environment:
      - AWS_REGION=us-west-2
      - AWS_BUCKET=chefbook-dev
      - FIRESTORE_BUCKET=
      - STORAGE_TYPE=s3 #POSSIBLE VALUES: s3, firebase, filesystem
      - NODE_ENV=development
      - VERBOSE=false
      - VERSION=development
      - POSTGRES_DB=recipesage_dev
      - POSTGRES_USER=recipesage_dev
      - POSTGRES_PASSWORD=recipesage_dev
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_SSL=false
      - POSTGRES_LOGGING=true
      - DATABASE_URL=postgresql://recipesage_dev:recipesage_dev@postgres:5432/recipesage_dev
      - GCM_KEYPAIR
      - SENTRY_SAMPLE_RATE=0
      - GRIP_URL=http://pushpin:5561/
      - GRIP_KEY=changeme
      - SEARCH_PROVIDER=typesense
      - ELASTIC_CONN=http://elastic:recipesage_dev@elasticsearch:9200
      - ELASTIC_PASSWORD=recipesage_dev
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_API_KEY=recipesage_dev
      - 'TYPESENSE_NODES=[{"host": "typesense", "port": 8108, "protocol": "http"}]'
      - TYPESENSE_API_KEY=recipesage_dev
      - BROWSERLESS_HOST=browserless
      - BROWSERLESS_PORT=3000
      - BROWSERLESS_TOKEN=recipesage_dev
      - INGREDIENT_INSTRUCTION_CLASSIFIER_URL=http://ingredient-instruction-classifier:3000/
    env_file:
      - ./.env
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=recipesage_dev
      - "ES_JAVA_OPTS=-Xms1500m -Xmx1500m"
      - xpack.security.enabled=false
    ports:
      - 9200:9200
  meilisearch:
    image: getmeili/meilisearch:v1.0
    environment:
      - MEILI_MASTER_KEY=recipesage_dev
  typesense:
    image: typesense/typesense:0.24.1
    volumes:
      - typesense-data:/data
    command: "--data-dir /data --api-key=recipesage_dev --enable-cors"
  kibana:
    image: kibana:8.4.3
    ports:
      - 5601:5601
  pushpin:
    image: fanout/pushpin:1.27.0
    environment:
      - target=backend:3000
    ports:
      - "7999:7999"
      - "5560-5563:5560-5563"
  postgres:
    image: postgres
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=recipesage_dev
      - POSTGRES_USER=recipesage_dev
      - POSTGRES_PASSWORD=recipesage_dev
  browserless:
    image: browserless/chrome:1.53.0-chrome-stable
    environment:
      - MAX_CONCURRENT_SESSIONS=3
      - MAX_QUEUE_LENGTH=10
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_LAUNCH_ARGS=["--disable-web-security"]
      - WORKSPACE_DELETE_EXPIRED=true
      - WORKSPACE_EXPIRE_DAYS=1
      - EXIT_ON_HEALTH_FAILURE=true
      - PREBOOT_CHROME=true
      - KEEP_ALIVE=true
      - FUNCTION_ENABLE_INCOGNITO_MODE=true
      - TOKEN=recipesage_dev
  ingredient-instruction-classifier:
    image: julianpoy/ingredient-instruction-classifier:latest

volumes:
  typesense-data:
