apiVersion: batch/v1
kind: CronJob
metadata:
  name: index-recipes-cron
spec:
  schedule: "0 6 * * 2"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: index-recipes-cron-runner
              image: julianpoy/recipesage:api-v2.11.0-beta24
              command: ["npx"]
              args:
                [
                  "--yes",
                  "ts-node",
                  "--swc",
                  "--project",
                  "packages/backend/tsconfig.json",
                  "packages/backend/src/index.app.ts",
                ]
              resources:
                requests:
                  cpu: 50m
                  memory: 100Mi
                limits:
                  cpu: 100m
                  memory: 1G
              envFrom:
                - secretRef:
                    name: rs-api-env
              env:
                - name: SEARCH_PROVIDER
                  value: typesense
                - name: STORAGE_TYPE
                  value: s3
                - name: TYPESENSE_NODES
                  value: '[{"host": "rs-typesense", "port": 8108, "protocol": "http"}]'
              volumeMounts:
                - name: firebase-credentials
                  mountPath: /app/.credentials/firebase.json
                  subPath: firebase-credentials.json
          volumes:
            - name: firebase-credentials
              configMap:
                name: firebase-credentials
          restartPolicy: Never
          imagePullSecrets:
            - name: myregistrykey
