apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-$RELEASE_TAG
spec:
  template:
    spec:
      containers:
        - name: migrate-$RELEASE_TAG
          image: julianpoy/recipesage:api-$RELEASE_TAG
          command: ["npx"]
          args: ["prisma", "migrate", "deploy"]
          resources:
            requests:
              cpu: 250m
              memory: 300Mi
            limits:
              cpu: 1
              memory: 1G
          envFrom:
            - secretRef:
                name: rs-api-env
          volumeMounts:
            - name: firebase-credentials
              mountPath: /app/.credentials/firebase.json
              subPath: firebase-credentials.json
      volumes:
        - name: firebase-credentials
          configMap:
            name: firebase-credentials
      restartPolicy: Never
      imagePullSecrets:
        - name: myregistrykey
