apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-pushpin
  labels:
    app: rs-pushpin
spec:
  selector:
    matchLabels:
      app: rs-pushpin
  template:
    metadata:
      labels:
        app: rs-pushpin
    spec:
      containers:
        - name: rs-pushpin
          image: julianpoy/pushpin:2023-09-17
          command: ["/bin/sh", "-c"]
          args:
            [
              "sed -i 's/sig_key=changeme/sig_key=$(GRIP_KEY)/' /etc/pushpin/pushpin.conf && echo '* rs-api:3000,over_http' > /etc/pushpin/routes && pushpin --merge-output",
            ]
          env:
            - name: GRIP_KEY
              valueFrom:
                secretKeyRef:
                  name: rs-pushpin-env
                  key: GRIP_KEY
          ports:
            - containerPort: 7999
            - containerPort: 5561
          resources:
            requests:
              cpu: 50m
              memory: 15Mi
            limits:
              cpu: 200m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rs-pushpin
spec:
  type: ClusterIP
  selector:
    app: rs-pushpin
  ports:
    - name: ws-connector
      protocol: TCP
      port: 7999
      targetPort: 7999
    - name: broadcast-connector
      protocol: TCP
      port: 5561
      targetPort: 5561
