name: Deploy to api.beta.recipesage.com

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: prod
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save 43e06009-6d1b-40cb-abbc-38736cc6746c

      - name: Deploy
        run: ./scripts/deploy/deploy_tag.sh api-beta ${{ inputs.tag }}
